// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qrxfgpzxxkvckvrwbhml.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFyeGZncHp4eGt2Y2t2cndiaG1sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzOTYwNjEsImV4cCI6MjA2MTk3MjA2MX0.CSkSK8_ua0O79aspRFdPOirtZzMfToFerBHKj66zOC8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);